spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://43.201.173.195:3306/mysqldb
#    username: pocket
    url: jdbc:mysql://localhost:3306/mysqlDb
    username: root
    password: mysqldb

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: none
        format_sql: true
        naming:
          physical-strategy: com.aaa.admin.config.NamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: trace

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6537b83f0a511fe480aa2935332bdc93
            client-secret: shHhhIDjXx7BJHiwbtnaCt1hM5JQiYk6
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

          naver:
            client-id: vSiH6o_RwIudwARHyO8k
            client-secret: NHaiXXMCgD
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M

springdoc:
  version: v1.0.0
  swagger-ui:
  packages-to-scan: com.project.assetManage