spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysqlDb
    username: root
    password: mysqldb

jpa:
  generate-ddl: true
  show-sql: true
  properties:
    hibernate:
      hbm2ddl.auto: create
      format_sql: true
      physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  logging.level:
    org.hibernate.SQL: debug