spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://43.201.173.195:3306/mysqldb
    url: jdbc:mysql://localhost:3306/mysqlDbls
#    username: pocket
    username: root
    password: mysqldb

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: none
        format_sql: true
        naming:
          physical-strategy: com.aaa.admin.config.NamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: trace

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M

springdoc:
  version: v1.0.0
  swagger-ui:
  packages-to-scan: com.project.assetManage